from pydantic import BaseModel, Field


class MetaData(BaseModel):
    """
    MetaData provides metadata for cache results, primarily for use in semantic
    cache wrappers or reranking pipelines.

    Attributes:
        prompt (str): The cache key text or query string.
        vector_distance (float): The semantic distance from the vector index
            (lower values indicate higher similarity).
        source (str): The source of the response ("cache" for cache hits, "llm"
            for responses generated by a language model).
    """

    prompt: str
    vector_distance: float
    source: str


class CacheResult(BaseModel):
    """
    CacheResult contains the standardized output from a cache lookup or an LLM fallback,
    including the response and associated metadata.

    Attributes:
        response (str): The cached response text (or LLM-generated if no cache hit).
        metadata (MetaData): The associated metadata object with information about
            prompt, vector distance, and source.
    """

    response: str
    metadata: MetaData
